"""add display_number to users, unique client_id on conversations

Revision ID: fecbfacb82df
Revises: 81dfc50b0068
Create Date: 2026-07-15 14:30:55.909052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecbfacb82df'
down_revision: Union[str, Sequence[str], None] = '81dfc50b0068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversations', ['client_id'])
    op.add_column('users', sa.Column('display_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['display_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'display_number')
    op.drop_constraint(None, 'conversations', type_='unique')
    # ### end Alembic commands ###
